### PR TITLE
Remove sa_ prefix

### PR DESCRIPTION
**Pull request by paramite**
We should not need to prefix metric with the deprecated framework abbreviation.

### CODE REVIEW

**Comment by leifmadsen** [comment]
I think our decisions are fix it now, or never fix it. Fixing it after GA and we have a customer using it, and dealing with the upgrades and such I think is going to cause all sorts of issues.

Personally I'd like to fix this now, but I also don't think we have the time to test this right now and validate everything.

I'd be ok with just seeing this go in, and then dealing with any fall out during our testing cycle, but that's probably a bit cowboy-esque this close to release.

**Comment by csibbitt** [comment]
I'll take on the task of posting the related PRs that I pointed out already and then I'll change my review here once they are in place.

**Comment by csibbitt** [comment]
Found some more: https://github.com/infrawatch/dashboards/blob/master/rhos-dashboard.yaml.template#L97

**Comment by csibbitt** [comment]
Alright, I've linked three PRs above to address this prefix change, and I've tested the only one that's functionally important, so I'm happy to let this merge now as long as https://github.com/infrawatch/service-telemetry-operator/pull/63 merges with it.

**Comment by csibbitt** [comment]
[Changes to smoketest/perftest/docs to remove "sa_" from the metrics prefix](https://trello.com/c/WKDRSOJX/928-changes-to-smoketest-perftest-docs-to-remove-sa-from-the-metrics-prefix)

**Pull request merged**
