### PR TITLE
Set a deterministic ID to prevent duplicate events

### PR DESCRIPTION
**Pull request by csibbitt**
Currently when multiple SGs are running in HA mode, each of them writes their own copy of events into ElasticSearch. By generating a document ID based on the content of the document itself, we can prevent duplicates from appearing.

### CODE REVIEW

**Comment by leifmadsen** [comment]
What happens in an environment that was using the SG prior to this change, and then the same environment updates to this change? What are the implications?

Curious just because we're going to have to start figuring out how to manage these types of scenarios where we fix something, but have environments with old logic moving to new logic. Want to make sure we don't surprise ourselves with future escalations :)

**Review by leifmadsen — APPROVED** [review]

**Comment by csibbitt** [comment]
# Testing

Tested this using the STF smoketest to generate events.

## Test 1 - Non HA, no patches

This is the default mode today and works fine.

```
$ oc exec elasticsearch-es-default-0 -- curl -sk -u "elastic:${ELASTICSEARCH_AUTH_PASS}" -X DELETE "https://localhost:9200/collectd_interface_if/"
$ ./smoketest.sh 

$ oc exec elasticsearch-es-default-0 -- curl -sk -u "elastic:${ELASTICSEARCH_AUTH_PASS}" -X GET "https://localhost:9200/collectd_interface_if/_search?size=100&pretty=true" -H 'Content-Type: application/json' -d "$QUERY" | grep startsAt | sort
[...]
          "startsAt" : "2020-09-08T15:40:40.087184711Z"
          "startsAt" : "2020-09-08T15:40:41.087156243Z"
          "startsAt" : "2020-09-08T15:40:42.087151849Z"
          "startsAt" : "2020-09-08T15:40:43.087234671Z"
```
We get 1 event/second in elasticsearch.

## Test 2 - Add a second SG, no patches

If I set up two Smart Gateways for High Availability, then we start getting duplicate events.

```
$ oc get po  | grep collectd-notification
stf-default-collectd-notification-smartgateway-69cc45f6b7-fxlsb   1/1     Running            0          30s
stf-default-collectd-notification-smartgateway-69cc45f6b7-rzh2r   1/1     Running            3          26d

$ oc exec elasticsearch-es-default-0 -- curl -sk -u "elastic:${ELASTICSEARCH_AUTH_PASS}" -X DELETE "https://localhost:9200/collectd_interface_if/"
$ ./smoketest.sh 

$ oc exec elasticsearch-es-default-0 -- curl -sk -u "elastic:${ELASTICSEARCH_AUTH_PASS}" -X GET "https://localhost:9200/collectd_interface_if/_search?size=100&pretty=true" -H 'Content-Type: application/json' -d "$QUERY" | grep startsAt | sort
[...]
          "startsAt" : "2020-09-08T15:46:01.099592618Z"
          "startsAt" : "2020-09-08T15:46:01.099592618Z"
          "startsAt" : "2020-09-08T15:46:02.099591327Z"
          "startsAt" : "2020-09-08T15:46:02.099591327Z"
          "startsAt" : "2020-09-08T15:46:03.099621314Z"
          "startsAt" : "2020-09-08T15:46:03.099621314Z"
          "startsAt" : "2020-09-08T15:46:04.099596752Z"
          "startsAt" : "2020-09-08T15:46:04.099596752Z"
```
Now we get 2 events/second, each one being written twice. 

Here is a full copy of a duplicate event:
```
      {                                                                                                                                                                           
        "_index" : "collectd_interface_if",
        "_type" : "event",
        "_id" : "12637c89-1025-49ed-a5dc-7da2a34774bc",
        "_score" : 0.0,
        "_source" : {
          "annotations" : {
            "CurrentValue" : "0",
            "DataSource" : "rx",
            "FailureMax" : "0",
            "FailureMin" : "nan",
            "WarningMax" : "nan",
            "WarningMin" : "nan",
            "summary" : "Host stf-smoketest-smoke1-9bqzt, plugin interface (instance lo) type if_octets: All data sources are within range again. Current value of \"rx\" is 0.000000."
          },
          "labels" : {
            "alertname" : "collectd_interface_if_octets",
            "instance" : "stf-smoketest-smoke1-9bqzt",
            "interface" : "lo",
            "service" : "collectd",
            "severity" : "OKAY"
          },
          "startsAt" : "2020-09-08T15:46:04.099596752Z"
        }
      },
      {
        "_index" : "collectd_interface_if",
        "_type" : "event",
        "_id" : "456bc577-858c-408e-8413-629cab01e82a",
        "_score" : 0.0,
        "_source" : {
          "annotations" : {
            "CurrentValue" : "0",
            "DataSource" : "rx",
            "FailureMax" : "0",
            "FailureMin" : "nan",
            "WarningMax" : "nan",
            "WarningMin" : "nan",
            "summary" : "Host stf-smoketest-smoke1-9bqzt, plugin interface (instance lo) type if_octets: All data sources are within range again. Current value of \"rx\" is 0.000000."
          },
          "labels" : {
            "alertname" : "collectd_interface_if_octets",
            "instance" : "stf-smoketest-smoke1-9bqzt",
            "interface" : "lo",
            "service" : "collectd",
            "severity" : "OKAY"
          },
          "startsAt" : "2020-09-08T15:46:04.099596752Z"
        }
      }
```

## Test 3 - Deploy patched SGs

I perform a local build of this branch, push it into my registry, and restart the pods to use it.

```
$ oc get po  | grep collectd-notification
stf-default-collectd-notification-smartgateway-5f67d94f54-lbx9x   1/1     Running            0          4s
stf-default-collectd-notification-smartgateway-5f67d94f54-mrgpr   1/1     Running            0          14s

$ oc exec elasticsearch-es-default-0 -- curl -sk -u "elastic:${ELASTICSEARCH_AUTH_PASS}" -X DELETE "https://localhost:9200/collectd_interface_if/"
$ ./smoketest.sh 

$ oc exec elasticsearch-es-default-0 -- curl -sk -u "elastic:${ELASTICSEARCH_AUTH_PASS}" -X GET "https://localhost:9200/collectd_interface_if/_search?size=100&pretty=true" -H 'Content-Type: application/json' -d "$QUERY" | grep startsAt | sort
[...]
          "startsAt" : "2020-09-08T19:26:31.369204882Z"
          "startsAt" : "2020-09-08T19:26:32.369240631Z"
          "startsAt" : "2020-09-08T19:26:33.369199484Z"
          "startsAt" : "2020-09-08T19:26:34.369220165Z"
```

The duplicates are gone, and here you can see the new _id field:

      {
        "_index" : "collectd_interface_if",
        "_type" : "event",
        "_id" : "1f50f91384f4ac935620011c4dac42ddb6368360",
        "_score" : 0.0,
        "_source" : {
          "annotations" : {
            "CurrentValue" : "0",
            "DataSource" : "rx",
            "FailureMax" : "0",
            "FailureMin" : "nan",
            "WarningMax" : "nan",
            "WarningMin" : "nan",
            "summary" : "Host stf-smoketest-smoke1-6dm9k, plugin interface (instance lo) type if_octets: All data sources are within range again. Current value of \"rx\" is 0.000000."
          },
          "labels" : {
            "alertname" : "collectd_interface_if_octets",
            "instance" : "stf-smoketest-smoke1-6dm9k",
            "interface" : "lo",
            "service" : "collectd",
            "severity" : "OKAY"
          },
          "startsAt" : "2020-09-08T19:26:48.369174837Z"
        }
```

**Comment by leifmadsen** [comment]
Based on what I'm seeing in the test output, it looks like everything should _just work_ going forward even in a pre- and post- world?

**Comment by csibbitt** [comment]
> What happens in an environment that was using the SG prior to this change, and then the same environment updates to this change? What are the implications?

A few points on implications:

* In STF there is currently no supported way of running two SGs, so no one should be getting the duplicates yet
* If someone WERE running multiple SGs, then events prior to the update would be duplicated in ES, and then after the update they wouldn't be. Nothing in STF cares about reading events from ElasticSearch, so the only implication I can imagine is if someone has already set up something downstream to deal with the de-duplication, which would now be useless.
* In the worst case, duplicates or no, perhaps a downstream system has come to (dangerously) depend on the format of the existing ids, and in that case their automation would break. Depending on the format or content of opaque primary keys is a pretty bad code smell, so it stretches the imagination to invent scenarios where this might have occurred. 

I think it's safe.

**Comment by csibbitt** [comment]
[Adjust SmartGateway to create document ID for events](https://trello.com/c/pdzDAx3w/825-adjust-smartgateway-to-create-document-id-for-events)

**Comment by leifmadsen** [comment]
Perfect thanks. I agree, this should be a NoOp() to risk. I wasn't sure (until I saw your comment) exactly what the data changes were. Since it's just an _id field format change, this does appear to be safe. Thanks!

**Comment by pleimer** [comment]
How exactly is this ensuring that only one metric per second is being written to ES in HA mode? I might just be being dense here, but all I see is a new type of uuid being generated, which would have been unique in the original example except that the timestamp on the event would be exactly the same. The results of your test are evident of course, I am just not sure how this patch is creating that result.

**Comment by csibbitt** [comment]
> How exactly is this ensuring that only one metric per second is being written to ES in HA mode? I might just be being dense here, but all I see is a new type of uuid being generated, which would have been unique in the original example except that the timestamp on the event would be exactly the same. The results of your test are evident of course, I am just not sure how this patch is creating that result.

Previously, each SG would write it's own copy of the event, having generated a unique UUIDv4-based _id field for the document, resulting in two totally distinct documents for the same event that differ only by their _id. Now, the _id is generated based on the data in the document itself, so the second SG goes to write the document it simply updates the existing one with the same _id, rather than creating duplicates.

More detail on this approach can be found here: https://www.elastic.co/blog/efficient-duplicate-prevention-for-event-based-data-in-elasticsearch

**Review by pleimer — APPROVED** [review]
Makes total sense thanks for the explanation

**Pull request merged**
